Add Create Release GH Action
sachinsharmaepisource/GH-Actions1 pull request #1
Opened 2021-01-14 11:11 UTC by sachinsharmaepisource

### Problem: 
When the master branch and develop branch are merged and current version > last version, than a new release is created with description as embedded PRs Titles.

Requirements:
- Python (PyGithub)
- GH Action (YML)
- DockerFile

### Flowchart
Feature branch -(merge)> Develop branch -(merge)> Master branch
----------------------------------------------------------- Here GH Action Initiates

### Key Features:

- Extracts last_version from latest release and current_version from version.ini file
- Compare last_version and current_version
> If current_version > last_version:             Action will create a new release
> Else:                                                          No change

2021-01-15 02:39 UTC, Prakshi-epi commented on .github/actions/createRelease/main.py
> +  requiremnet:
spell check

2021-01-15 02:43 UTC, Prakshi-epi commented on .github/actions/createRelease/main.py
> +def get_datetime_now():
@sachinsharmaepisource Docstring is missing in all the functions. Refer to this guide on how to add a docstring to your code: https://numpydoc.readthedocs.io/en/latest/format.html

Also, add inline comments wherever necessary. Inline comments are used to describe your custom logic or some additional case you have handled in your code.

2021-01-15 13:35 UTC, sachinsharmaepisource commented on .github/actions/createRelease/main.py
> +  requiremnet:
corrected 👍

2021-01-15 13:35 UTC, sachinsharmaepisource commented on .github/actions/createRelease/main.py
> +def get_datetime_now():
Added the docStrings and inline comments 🚀

2021-01-18 06:07 UTC, Prakshi-epi commented on .github/actions/createRelease/main.py
> +
@sachinsharmaepisource Rewrite this script using Python Classes and Objects. The code looks clean but needs refactoring in terms of structure.

2021-01-18 06:07 UTC, Prakshi-epi requested changes
Please have a look at comments

2021-01-18 07:38 UTC, sachinsharmaepisource commented on .github/actions/createRelease/main.py
> +
Hi Prakshi, I had updated the code with class and object structure.

2021-01-19 16:43 UTC, Prakshi-epi commented on .github/actions/createRelease/main.py
> +        If the latest release exists:
Please cross-check this statement. I think you mean `If the latest release doesn't' exists`

2021-01-19 16:46 UTC, Prakshi-epi commented on .github/workflows/main.yml
> +on:
Let's keep the condition to trigger the GitHub action on every commit in master branch
```
on:
  push:
    branches: [ master ]
```

2021-01-20 05:29 UTC, sachinsharmaepisource commented on .github/workflows/main.yml
> +on:
Updated with corrections mentioned

2021-02-03 15:51 UTC, closed without merging